SELECT
    COLUMN_NAME,
    ORDINAL_POSITION,
    IS_NULLABLE = CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END,
    DATA_TYPE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE
    TABLE_NAME = @TableName
AND TABLE_SCHEMA = @TableSchema
